#!/bin/bash
# Generate llms.txt for AI consumption
# Principle: systems-stewardship

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
KNOWLEDGE_DIR="$REPO_ROOT/knowledge"
OUTPUT_FILE="$KNOWLEDGE_DIR/llms.txt"

cat > "$OUTPUT_FILE" << 'EOF'
# Dotfiles AI Context

This file provides comprehensive context for AI agents working with this dotfiles repository.
Generated from the knowledge base to ensure AI agents have full understanding of principles, procedures, and available tools.

Repository: https://github.com/atxtechbro/dotfiles

EOF

echo "## Table of Contents" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "1. [Core Philosophy](#core-philosophy)" >> "$OUTPUT_FILE"
echo "2. [Principles](#principles)" >> "$OUTPUT_FILE"
echo "3. [Procedures](#procedures)" >> "$OUTPUT_FILE"
echo "4. [MCP Servers and Tools](#mcp-servers-and-tools)" >> "$OUTPUT_FILE"
echo "5. [Personalities](#personalities)" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Core Philosophy from main README
echo "## Core Philosophy" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
if [ -f "$REPO_ROOT/README.md" ]; then
    echo "### The Spilled Coffee Principle" >> "$OUTPUT_FILE"
    sed -n '/### The Spilled Coffee Principle/,/### The Snowball Method/p' "$REPO_ROOT/README.md" | head -n -1 >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    
    echo "### The Snowball Method" >> "$OUTPUT_FILE"
    sed -n '/### The Snowball Method/,/### The Versioning Mindset/p' "$REPO_ROOT/README.md" | head -n -1 >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    
    echo "### The Versioning Mindset" >> "$OUTPUT_FILE"
    sed -n '/### The Versioning Mindset/,/## Quick Start/p' "$REPO_ROOT/README.md" | head -n -1 >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
fi

# Throughput Definition (North Star)
echo "## Throughput Definition (The Goal)" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "Path: $KNOWLEDGE_DIR/throughput-definition.md" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
if [ -f "$KNOWLEDGE_DIR/throughput-definition.md" ]; then
    cat "$KNOWLEDGE_DIR/throughput-definition.md" >> "$OUTPUT_FILE"
fi
echo "" >> "$OUTPUT_FILE"

# Principles
echo "## Principles" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "Foundational truths that guide development across all projects." >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

for file in "$KNOWLEDGE_DIR/principles"/*.md; do
    if [ -f "$file" ] && [ "$(basename "$file")" != "README.md" ]; then
        filename=$(basename "$file")
        echo "### ${filename%.md}" >> "$OUTPUT_FILE"
        echo "Path: $file" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        cat "$file" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
    fi
done

# Procedures
echo "## Procedures" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "Actionable processes and workflows that evolve with experience." >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

for file in "$KNOWLEDGE_DIR/procedures"/*.md; do
    if [ -f "$file" ] && [ "$(basename "$file")" != "README.md" ]; then
        filename=$(basename "$file")
        echo "### ${filename%.md}" >> "$OUTPUT_FILE"
        echo "Path: $file" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        cat "$file" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
    fi
done

# MCP Servers and Tools
echo "## MCP Servers and Tools" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "Available MCP servers for AI agent capabilities." >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

if [ -f "$REPO_ROOT/mcp/README.md" ]; then
    cat "$REPO_ROOT/mcp/README.md" >> "$OUTPUT_FILE"
fi
echo "" >> "$OUTPUT_FILE"

# Tool Discovery (if it exists)
if [ -f "$REPO_ROOT/mcp/tool-discovery.md" ]; then
    echo "### Tool Discovery Guide" >> "$OUTPUT_FILE"
    echo "Path: $REPO_ROOT/mcp/tool-discovery.md" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    cat "$REPO_ROOT/mcp/tool-discovery.md" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
fi

# Personalities
echo "## Personalities" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "Consultant personas for specialized perspectives during retros and analysis." >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

for file in "$KNOWLEDGE_DIR/personalities"/*.md; do
    if [ -f "$file" ] && [ "$(basename "$file")" != "README.md" ]; then
        filename=$(basename "$file")
        echo "### ${filename%.md}" >> "$OUTPUT_FILE"
        echo "Path: $file" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        cat "$file" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
    fi
done

# Footer
cat >> "$OUTPUT_FILE" << EOF

---

Generated: $(date '+%Y-%m-%d %H:%M:%S')
Source: $REPO_ROOT/knowledge
This file is automatically regenerated by setup.sh to ensure AI agents have current context.
EOF

chmod 644 "$OUTPUT_FILE"
echo "Generated $OUTPUT_FILE"