name: Dotfiles Issue Triage
description: Automatically triage GitHub issues using Claude Code
on:
  issues:
    types: [opened, edited]

jobs:
  triage-issue:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare prompt with issue details
        run: |
          mkdir -p /tmp/claude-prompts
          
          ISSUE_AUTO_LABEL="${{ github.workspace }}/.github/workflow-prompts/issue-triage.md"
          
          cat "$ISSUE_AUTO_LABEL" | \
            sed "s|{{ REPO }}|${{ github.repository }}|g" | \
            sed "s|{{ ISSUE_NUMBER }}|${{ github.event.issue.number }}|g" \
            > /tmp/claude-prompts/triage-prompt.txt

      - name: Setup GitHub MCP Server
        run: |
          mkdir -p /tmp/mcp-config
          cat > /tmp/mcp-config/mcp-servers.json << 'EOF'
          {
            "mcpServers": {
              "github": {
                "command": "node",
                "args": ["${{ github.workspace }}/mcp/servers/github-mcp-server/dist/index.js"],
                "env": {
                  "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}"
                }
              }
            }
          }
          EOF

      - name: Run Claude Code for Issue Triage
        uses: anthropics/claude-code-action@beta
        with:
          prompt_file: /tmp/claude-prompts/triage-prompt.txt
          allowed_tools: "Bash(gh label list),mcp__github-write__get_issue,mcp__github-write__get_issue_comments,mcp__github-write__update_issue,mcp__github-write__search_issues,mcp__github-write__list_issues"
          timeout_minutes: "5"
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          model: claude-sonnet-4-20250514
          mcp_config: /tmp/mcp-config/mcp-servers.json
          claude_env: |
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}