name: Auto-Trigger Claude
description: Automatically trigger Claude to implement new issues (Ultimate OSE)
on:
  issues:
    types: [opened]

jobs:
  auto-trigger-claude:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    permissions:
      issues: write

    steps:
      - name: Auto-trigger Claude implementation
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '@claude Please implement this issue and create a PR.'
            });