name: Auto-Trigger Claude
description: Automatically trigger Claude to implement new issues (Ultimate OSE)
on:
  issues:
    types: [opened]

jobs:
  auto-trigger-claude:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    permissions:
      issues: write

    steps:
      - name: Auto-trigger Claude implementation
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.CLAUDE_TRIGGER_PAT }}
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '@claude Please implement this issue and CREATE the pull request automatically.\n\nRemember:\n- CREATE the PR automatically using mcp__github__create_pull_request (not gh cli)\n- Do NOT just provide a link - actually create the PR\n- Do NOT approve the PR (only humans approve)\n\nThis is OSE automation - the PR must be created automatically.'
            });