name: Auto-Trigger Claude
description: Automatically trigger Claude to implement new issues (Ultimate OSE)
on:
  issues:
    types: [opened]

jobs:
  auto-trigger-claude:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    permissions:
      issues: write

    steps:
      - name: Checkout repository (for composite action)
        uses: actions/checkout@v4
        
      - name: Auto-trigger Claude implementation
        uses: ./.github/actions/auto-trigger-claude
        with:
          github-token: ${{ secrets.CLAUDE_TRIGGER_PAT }}
          allowed-users: 'atxtechbro'
          pr-template-url: 'https://github.com/atxtechbro/dotfiles/blob/main/.github/PULL_REQUEST_TEMPLATE.md'