name: Auto-Trigger Claude
description: Automatically trigger Claude to implement new issues (Ultimate OSE)
on:
  issues:
    types: [opened]

jobs:
  auto-trigger-claude:
    # Gate: only run when Claude Code is explicitly enabled
    # Enable by setting repo variable: CLAUDE_CODE_SUBSCRIPTION=active
    # Also requires PAT secret to exist (prevents unsolicited comments)
    if: ${{ vars.CLAUDE_CODE_SUBSCRIPTION == 'active' && secrets.CLAUDE_TRIGGER_PAT != '' }}
    runs-on: ubuntu-latest
    timeout-minutes: 2
    permissions:
      issues: write

    steps:
      - name: Auto-trigger Claude implementation
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.CLAUDE_TRIGGER_PAT }}
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '@claude Please implement this issue and CREATE AN ACTUAL PULL REQUEST on GitHub.\n\n**IMPORTANT**: You MUST create a real PR on GitHub (not just provide a link to create one). use branch name according to repo guidelines such that branch name contains issue number suffix and is guaranteed to be unique. The PR must be created and visible at github.com/atxtechbro/dotfiles/pulls.\n\n**NOTE**: You now have access to the full knowledge base including all principles (tracer-bullets, versioning-mindset, OSE, etc.) and procedures (git-workflow, worktree-workflow, etc.). Use this context to create high-quality PRs that follow established patterns.\n\n**PR FORMAT**: Follow .github/PULL_REQUEST_TEMPLATE.md structure. Use heredoc to prevent escaped newlines. See knowledge/procedures/close-issue-procedure.md#creating-the-pull-request for the exact command format.'
            });
