name: Claude PR Review
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  claude-review:
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest

    steps:
      - name: Acknowledge review request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              // Add eyeball reaction to show Claude saw the request
              const reaction = await github.rest.reactions.createForIssueComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: context.payload.comment.id,
                content: 'eyes'
              });
              
              console.log(`✅ Successfully added eyeball reaction to comment ${context.payload.comment.id}`);
              console.log(`Reaction ID: ${reaction.data.id}`);
            } catch (error) {
              console.error(`❌ Failed to add reaction: ${error.message}`);
              console.error(`Comment ID: ${context.payload.comment.id}`);
              console.error(`Repository: ${context.repo.owner}/${context.repo.repo}`);
              // Don't fail the workflow if reaction fails
              // The review should still proceed
            }

      - uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}