name: Claude Delegation Label Cleanup
on:
  issue_comment:
    types: [created, edited]

jobs:
  remove-labels-on-delegation:
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    
    steps:
      - name: Remove labels after Claude delegation
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Remove all labels except those with ongoing behavioral significance
            const issue = context.payload.issue;
            const keepLabels = ['ai-generate', 'spike']; // Labels that affect workflows
            
            const currentLabels = issue.labels.map(l => l.name);
            const labelsToRemove = currentLabels.filter(l => !keepLabels.includes(l));
            
            for (const label of labelsToRemove) {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                name: label
              });
            }
            
            // Add a comment noting the delegation
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              body: '🤖 Labels cleaned up after Claude delegation (subtraction creates value)'
            });