name: Claude Code PR Generator

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to process'
        required: true
        type: number
  issues:
    types: [labeled]

jobs:
  generate-pr:
    if: ${{ github.event.label.name == 'ai-generate' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    timeout-minutes: 3  # Shorter timeout for hello world test
    permissions:
      contents: write
      issues: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Claude Code
        run: |
          npm install -g @anthropic-ai/claude-code
          echo "Claude Code installed, checking version:"
          claude --version || echo "Claude version command failed"

      - name: Simple Claude Hello World Test
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          CLAUDE_AUTH_TOKEN: ${{ secrets.CLAUDE_AUTH_TOKEN }}
        run: |
          echo "Running simple Claude hello world test"
          if [ -n "$ANTHROPIC_API_KEY" ] || [ -n "$CLAUDE_AUTH_TOKEN" ]; then
            echo "Authentication environment variables found"
          else
            echo "Missing Claude authentication. Please set ANTHROPIC_API_KEY or CLAUDE_AUTH_TOKEN in GitHub Secrets"
            exit 1
          fi
          
          # Simple hello world test
          echo "Running: claude -p \"Why is Austin such a great tech hub?\""
          claude -p "Why is Austin such a great tech hub?" --output-format text
          
          echo "Hello world test completed successfully"
