name: Claude Code PR Generator

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to process'
        required: true
        type: number
  issues:
    types: [labeled]

jobs:
  generate-pr:
    if: ${{ github.event.label.name == 'ai-generate' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup and run Claude Code
        uses: actions/github-script@v7
        with:
          script: |
            // Install Claude Code
            await exec.exec('npm install -g @anthropic-ai/claude-code');
            
            // Get issue details
            const issueNumber = context.payload.issue?.number || context.payload.inputs.issue_number;
            if (!issueNumber) {
              core.setFailed('No issue number provided');
              return;
            }
            
            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber
            });
            
            // Create branch
            const branchName = `ai-${issueNumber}`;
            await exec.exec('git config user.name "GitHub Action"');
            await exec.exec('git config user.email "action@github.com"');
            await exec.exec(`git checkout -b ${branchName}`);
            
            // Run Claude Code with minimal prompt
            const { stdout } = await exec.getExecOutput(
              'claude',
              [
                '-p',
                `Issue #${issueNumber}: ${issue.data.title}\n\n${issue.data.body}`,
                '--allowedTools', 'mcp__filesystem__*,mcp__github__*',
                '--system-prompt', '$(cat AmazonQ.md)',
                '--output-format', 'json'
              ]
            );
            
            const claudeResponse = JSON.parse(stdout).result;
            
            // Create PR
            const pr = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `AI: ${issue.data.title}`,
              body: `Resolves #${issueNumber}`,
              head: branchName,
              base: 'main'
            });
            
            // Comment on the issue
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: `Created PR: ${pr.data.html_url}`
            });
