name: Terminal Startup Test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
  # Run monthly to ensure continued compatibility
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  test-terminal-startup:
    name: Test Terminal Startup
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup test environment
        run: |
          # Create a fake home directory for testing
          mkdir -p /tmp/test-home
          export HOME=/tmp/test-home
          
          # Setup dotfiles
          ln -sf $GITHUB_WORKSPACE /tmp/test-home/dotfiles

      - name: Install minimal essential packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends git bash
          
      - name: Setup dotfiles
        run: |
          export HOME=/tmp/test-home
          
          # Create required directories
          mkdir -p $HOME/.config/nvim
          
          # Create symlinks (only the critical ones to save time)
          ln -sf $HOME/dotfiles/nvim/init.lua $HOME/.config/nvim/init.lua
          ln -sf $HOME/dotfiles/.bashrc $HOME/.bashrc
          ln -sf $HOME/dotfiles/.bash_aliases $HOME/.bash_aliases
          ln -sf $HOME/dotfiles/.bash_exports $HOME/.bash_exports
          ln -sf $HOME/dotfiles/.gitconfig $HOME/.gitconfig
          ln -sf $HOME/dotfiles/.tmux.conf $HOME/.tmux.conf

      - name: Run terminal startup test
        run: |
          export HOME=/tmp/test-home
          chmod +x $GITHUB_WORKSPACE/tests/terminal_startup_test.sh
          $GITHUB_WORKSPACE/tests/terminal_startup_test.sh
