name: Test Arch Linux Installation

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'arch-install.sh'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install shellcheck
        run: sudo apt-get install -y shellcheck
      
      - name: Lint installation scripts
        run: |
          shellcheck arch-install.sh

  test-in-container:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm git bash
      
      - name: Make scripts executable
        run: |
          chmod +x arch-install.sh
      
      - name: Validate arch-install.sh
        run: |
          # We can't run the full install script in CI, but we can check syntax
          bash -n arch-install.sh
